# -*- coding: utf-8 -*-
"""ml lab-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VeZ7lDv1HxF9atzC1SS_YNhq2hXweuJB
"""

import tensorflow as tf
from tensorflow.keras import layers, models

# 1. Load MNIST dataset
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

# 2. Normalize data (0–255 → 0–1)
X_train = X_train / 255.0
X_test = X_test / 255.0

# 3. Build ANN model
model = models.Sequential([
layers.Flatten(input_shape=(28, 28)), # Input layer
layers.Dense(64, activation='relu'), # Hidden layer
layers.Dense(10, activation='softmax') # Output layer
])

# 4. Compile (defines backpropagation settings)
model.compile(
optimizer='adam', # Gradient descent
loss='sparse_categorical_crossentropy', # Loss function
metrics=['accuracy']
)

# 5. Train model (backpropagation )
model.fit(X_train, y_train, epochs=5, batch_size=32)

# 6. Test model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)